### ISSUE TITLE
PDF (Black Box) Error Message(s)

### ISSUE THREAD

**Issue by Phantom11265** [clj-pdf/clj-pdf#168]
So when I try calling my main function that generates the PDF, if there are any errors it becomes a black box and doesn't give back any specific errors. However, I am also new to Clojure, and I've noticed that Clojure(s) error messages are a bit difficult sometimes to decipher. Besides the point; my error that comes up when I call a function named (generate-pdf) and it gives me a ClassCastException [trace missing]. Again, I'm not sure if this is a Clojure thing, or what. What I want to be fixed, if it's your clj-pdf, to maybe add better error messages. 
![image](https://user-images.githubusercontent.com/49042422/55188551-4bfc1500-5161-11e9-81e4-04200cdfe3b7.png)
![image](https://user-images.githubusercontent.com/49042422/55188585-633b0280-5161-11e9-9fd8-7f29b13c7f23.png)

**Comment by yogthos** [comment]
The class cast exception indicates that you're passing a wrong type somewhere, and the trace would help see where that happens exactly. So you need to figure out how to get the trace to see where the error originates.

I would recommend running your hand-entered! function from the REPL to see what it generates as well. 

The library does try to provide meaningful error messages when possible, but I need to know what caused the error in order to provide a better message for it.
