### ISSUE TITLE
add ability to pass margins/dimensions to collate

### ISSUE THREAD

**Issue by yogthos** [clj-pdf/clj-pdf#95]
The `collate` function will use the default dimensions of the first document, this may not be desirable when collating documents of different sizes.

**Comment by Kah0ona** [comment]
I had a problem with orientation in this collation function. I had custom size PDF's that i subsequently wanted to collate, and then all pages were rotated.

By [googling](https://stackoverflow.com/questions/48613837/how-to-merge-pdf-documents-with-correct-orientation?noredirect=1&lq=1#comment84229300_48613837) a bit, I found out that using `PdfCopy`, rather than using `PdfWriter`, both simplifies the collation function, and makes it independent of the size / orientation of the first document.

So I came up with this collation function. 

````clojure
(defn collate
  "usage: takes an output that can be a file name or an output stream followed by one or more documents
   that can be input streams, urls, filenames, or byte arrays."
  [& params]
    (let [[{:keys [author creator subject title]} out & pdfs]
          (if (map? (first params))
            params
            (into [{}] params))
          out (io/output-stream out)
          doc (Document.)
          wrt (PdfCopy. doc out)]
    (.open doc)
    (.getDirectContent wrt)
    (when title (.addTitle doc title))
    (when subject (.addSubject doc subject))
    (when author (.addAuthor doc author))
    (when creator (.addCreator doc creator))
    (doseq [pdf pdfs]
      (with-open [rdr (PdfReader. (io/input-stream pdf))]
        (dotimes [i (.getNumberOfPages rdr)]
          (let [page (.getImportedPage wrt rdr (inc i))]
            (.addPage wrt page)))))
    (.flush out)
    (.close doc)
    (.close out)))
````

Do you want me to make a PR?

**Comment by Kah0ona** [comment]
I made a PR :-)

**Comment by yogthos** [comment]
Thanks for the pr, the new way is definitely an improvement. :)
